from typing import Dict, Any, Optional
from mcp.server.fastmcp import Context
from app.core.logging import get_logger
from ._helpers import _error_result
from .gmail_fetch_thread import tool as fetch_thread
from .gmail_create_draft import tool as create_draft

logger = get_logger(__name__)

async def tool(
    user_id: str = "me",
    thread_id: str = "",
    reply_body: str = "",
    reply_html: Optional[str] = None,
    ctx: Context = None,
) -> Dict[str, Any]:
    """
    Generate a reply draft for a thread.

    Args:
        user_id: Gmail user ID
        thread_id: Thread to reply to
        reply_body: The reply text (typically AI-generated by the agent)
        reply_html: Optional HTML version of the reply

    Returns:
        Created reply draft ID.
    """
    if not thread_id:
        return _error_result("gmail_generate_reply_draft", "thread_id is required")
    if not reply_body:
        return _error_result("gmail_generate_reply_draft", "reply_body is required")
    try:
        thread_result = await fetch_thread(
            user_id=user_id, thread_id=thread_id, ctx=ctx
        )
        if thread_result["status"] != "OK":
            return thread_result
        thread_data = thread_result["data"]
        messages = thread_data.get("messages", [])
        if not messages:
            return _error_result("gmail_generate_reply_draft",
                                 "Thread has no messages")
        last_msg = messages[-1]
        reply_to = last_msg.get("from", "")
        subject = thread_data.get("subject", "")
        if not subject.lower().startswith("re:"):
            subject = f"Re: {subject}"
        return await create_draft(
            user_id=user_id, to=reply_to, subject=subject,
            body=reply_body, html_body=reply_html,
            thread_id=thread_id, ctx=ctx,
        )
    except Exception as e:
        logger.error("gmail_generate_reply_draft failed", error=str(e))
        return _error_result("gmail_generate_reply_draft", str(e))
